### PR TITLE
Actually ship type annotations

### LINKED ISSUE #4: Are type annotations shipped?
I think type annotations should be shipped, but I haven't checked. Might need to include a `py.typed` for it to work.

Once this question is resolved, #1 should be done and release is a go.

### PR DESCRIPTION
**Pull request by elihunter173**
Resolves #4 

This is blocked on https://github.com/python-poetry/poetry-core/pull/46 landing I believe. Alternatively, I could switch away from poetry entirely, but I'd rather not.

### CODE REVIEW

**Comment by elihunter173** [comment]
Actually, I'll leave this PR up, but I'm going to create a new one that switches to a `setup.py`. When poetry begins better supporting `py.typed` files, I'll switch back.

**Comment by elihunter173** [comment]
Actually, on second thought I want to stay with poetry. I'll ship `1.0.0` with no type annotations and `1.1.0` will have type annotations.

**Comment by atollk** [comment]
It seems that it is possible to include the `py.typed` marker even without the mentioned poetry PR merged. Does the wheel that poetry builds for you contain `py.typed`?

**Comment by elihunter173** [comment]
The wheel does (as does the sdist), but when I did local testing using the path and this branch mypy couldn't find the type annotations when checking a file like this

```python
import java_manifest
```

That may be because I messed up something since I've never tried to ship type annotations in a poetry-based project, but when I read the `setup.py` in the sdist I noticed that it didn't include the `package_data` line mentioned [here](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages) in the mypy docs, which lead me to finding the linked PR

**Comment by atollk** [comment]
Yes, the discrepancy between how `setup.py` should look and how it does look is what motivated me to make that PR. To my understanding, it only matters to mypy whether the `py.typed` file actually exists. 
Just to be clear: when you call mypy with `--follow-imports=silent` and the installed package contains `py.typed` (in the `venv/Lib/site-packages` directory), you still receive an error on the import line?

**Comment by elihunter173** [comment]
I just tried again and yes I do. Here is how I reproduced the error

```
$ python -m venv venv
$ . ./venv/bin/activate
(venv) $ echo "import java_manifest; print(java_manifest.__version__)" > test.py
(venv) $ pip install git+https://github.com/elihunter173/java-manifest-py.git@typing
(venv) $ python test.py
0.1.0
(venv) $ mypy --follow-imports=silent test.py
test.py:1: error: Cannot find implementation or library stub for module named 'java_manifest'
test.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
(venv) $ ls ./venv/lib/python3.8/site-packages/java_manifest
__init__.py  __pycache__/  py.typed
```

Edit: I accidentally wrote `bin/venv/activate` instead of `venv/bin/activate` in my original list of commands.

**Comment by atollk** [comment]
I cannot reproduce this with mypy 0.782. I am reported no error.
Either way, this doesn't seem like a poetry-related issue since the file is included correctly in the built package.

**Comment by elihunter173** [comment]
It might be a NixOS (my distro) issue then. I'll try on one of my ubuntu boxes and do more digging.

Thanks for your help!

**Comment by elihunter173** [comment]
Confirmed working on my ubuntu box. I don't know why it doesn't work on NixOS yet

**Pull request merged**
